version: "3.9"
services:
  Postgres-work:
    image: postgres:latest
    environment:
      POSTGRES_DB: "shilov"
      POSTGRES_USER: "shilov"
      POSTGRES_PASSWORD: "shilov"
    expose:
      - "5440"
    ports:
      - "5440:5440"
    restart: on-failure
    command: -p 5440